### ISSUE TITLE
Shape mismatch

### ISSUE THREAD

**Issue by ivs-pychen** [schissmantics/yolo-tf2#35]
**Describe the current behavior**
I try to train yolov3 on VOC. But I got the following error in the first epoch.
**Describe the expected behavior**
```
2021-09-06 23:38:36,989 yolo_tf2.utils.common.train +467: INFO     [29124] Starting training ...
2021-09-06 23:38:36,989 yolo_tf2.utils.common.train +469: INFO     [29124] Generating new anchors ...
2021-09-06 23:38:37,119 yolo_tf2.utils.common.parse_voc_folder +110: INFO     [29124] Labels retrieved from cache:
person         22848
chair           4488
car             4136
bottle          2195
dog             2136
bird            1870
pottedplant     1827
cat             1666
boat            1457
sheep           1437
aeroplane       1333
sofa            1266
tvmonitor       1260
bicycle         1255
horse           1209
motorbike       1191
cow             1127
diningtable     1110
train           1032
bus              957
Name: object_name, dtype: int64
Iteration: 0 Loss: 379654.1707438685
Iteration: 1 Loss: 39912.55916830299
Iteration: 2 Loss: 9423.08513675976
Iteration: 3 Loss: 5752.443710062272
Iteration: 4 Loss: 4324.45786485536
Iteration: 5 Loss: 3750.1242674337377
Iteration: 6 Loss: 3146.412187599276
Iteration: 7 Loss: 2285.100366501147
Iteration: 8 Loss: 1918.889177090881
Iteration: 9 Loss: 1850.1752348520588
Iteration: 10 Loss: 1602.8338905955159
Iteration: 11 Loss: 1332.2971528592223
Iteration: 12 Loss: 1012.7892973153108
Iteration: 13 Loss: 1057.7347910542223
Iteration: 14 Loss: 691.2083918777071
Iteration: 15 Loss: 663.6456678643282
Iteration: 16 Loss: 740.618478872901
Iteration: 17 Loss: 867.0765515845785
Iteration: 18 Loss: 717.6141476978081
Iteration: 19 Loss: 720.0821714844607
Iteration: 20 Loss: 648.1284427962107
Iteration: 21 Loss: 670.5422464941743
Iteration: 22 Loss: 561.4074154636859
Iteration: 23 Loss: 849.7878022124378
Iteration: 24 Loss: 704.0524903299417
Iteration: 25 Loss: 868.3320090824227
Iteration: 26 Loss: 634.8547226922037
Iteration: 27 Loss: 685.9992644936723
Iteration: 28 Loss: 760.4417375224959
Iteration: 29 Loss: 301.0808441728114
Iteration: 30 Loss: 905.037321984565
Iteration: 31 Loss: 567.9367808607134
Iteration: 32 Loss: 478.1533365398513
Iteration: 33 Loss: 407.6605056162515
Iteration: 34 Loss: 523.1780702383633
Iteration: 35 Loss: 397.6463098990634
Iteration: 36 Loss: 321.1173194844014
Iteration: 37 Loss: 399.16796010857945
Iteration: 38 Loss: 394.56150735180233
Iteration: 39 Loss: 257.6874144761185
Iteration: 40 Loss: 376.96176976975073
Iteration: 41 Loss: 573.9876517452831
Iteration: 42 Loss: 284.9044815251612
Iteration: 43 Loss: 207.5307146231646
Iteration: 44 Loss: 312.37578577433845
Iteration: 45 Loss: 300.19495573412814
Iteration: 46 Loss: 460.8161260454617
Iteration: 47 Loss: 561.9508869723252
Iteration: 48 Loss: 562.4887923148801
Iteration: 49 Loss: 375.9842639623483
Iteration: 50 Loss: 523.3163999412953
Iteration: 51 Loss: 497.4288540153239
Iteration: 52 Loss: 347.2580486709243
Iteration: 53 Loss: 334.1310969218943
Iteration: 54 Loss: 165.91563829680442
Iteration: 55 Loss: 232.01878525312745
Iteration: 56 Loss: 378.5765296019512
Iteration: 57 Loss: 235.11361317180243
Iteration: 58 Loss: 202.95298527884128
Iteration: 59 Loss: 225.73153164307837
Iteration: 60 Loss: 216.5832591175894
Iteration: 61 Loss: 170.57110016304864
Iteration: 62 Loss: 113.8456841523198
Iteration: 63 Loss: 212.46032487914903
Iteration: 64 Loss: 137.55926713539225
Iteration: 65 Loss: 140.5131619102409
Iteration: 66 Loss: 98.47072672601881
Iteration: 67 Loss: 67.33065231458639
Iteration: 68 Loss: 26.603402782925393
Iteration: 69 Loss: 34.9795999769397
Iteration: 70 Loss: 125.90680789554555
Iteration: 71 Loss: 143.69301154568524
Iteration: 72 Loss: 99.09388152677873
Iteration: 73 Loss: 58.09877197740613
Iteration: 74 Loss: 39.723116187039736
Iteration: 75 Loss: 46.36278205940381
Iteration: 76 Loss: 96.05240045005019
Iteration: 77 Loss: 22.648917085130716
Iteration: 78 Loss: 0.0
2021-09-06 23:38:39,980 yolo_tf2.utils.common.k_means +64: INFO     [29124] Generated 9 anchors in 79 iterations
2021-09-06 23:38:39,982 yolo_tf2.utils.common.wrapper +64: INFO     [29124] visualized execution time: 2.52873588912189 seconds
2021-09-06 23:38:39,982 yolo_tf2.utils.common.generate_new_anchors +162: INFO     [29124] Changed default anchors to generated ones
2021-09-06 23:38:40.046777: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-09-06 23:38:40.047101: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-09-06 23:38:40.047114: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      
2021-09-06 23:38:41,286 yolo_tf2.utils.common.create_models +575: INFO     [29124] Training and inference models created
2021-09-06 23:38:41,287 yolo_tf2.utils.common.wrapper +64: INFO     [29124] create_models execution time: 1.3037840160541236 seconds
2021-09-06 23:38:41,288 yolo_tf2.utils.common.load_weights +600: INFO     [29124] Loading pre-trained weights ...
100%    246637548/246714648
2021-09-06 23:38:41,835 yolo_tf2.utils.common.load_weights +667: INFO     [29124] 
Loaded weights: weights/yolov3_voc_lr3/yolov3-voc.weights ... success
2021-09-06 23:38:41,835 yolo_tf2.utils.common.wrapper +64: INFO     [29124] load_weights execution time: 0.548234929330647 seconds
2021-09-06 23:38:41,835 yolo_tf2.utils.common.create_new_dataset +365: INFO     [29124] Generating new dataset ...
2021-09-06 23:38:41,909 yolo_tf2.utils.common.parse_voc_folder +110: INFO     [29124] Labels retrieved from cache:
person         22848
chair           4488
car             4136
bottle          2195
dog             2136
bird            1870
pottedplant     1827
cat             1666
boat            1457
sheep           1437
aeroplane       1333
sofa            1266
tvmonitor       1260
bicycle         1255
horse           1209
motorbike       1191
cow             1127
diningtable     1110
train           1032
bus              957
Name: object_name, dtype: int64
Processing test_train.tfrecord
Building example: 15495/15495 ... 004192 100% completedleted
/home/ivs523pychen/IVS-TF2/yolo_tf2/utils/dataset_handlers.py:209: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  groups = np.array(data.groupby('image_path'))
2021-09-06 23:43:53,503 yolo_tf2.utils.common.save_tfr +227: INFO     [29124] Saved training TFRecord: /home/ivs523pychen/IVS-TF2/data/tfrecords/test_train.tfrecord
Processing test_test.tfrecord
Building example: 6641/6641 ... 2010_003884 100% completed
2021-09-06 23:46:03,824 yolo_tf2.utils.common.save_tfr +229: INFO     [29124] Saved validation TFRecord: /home/ivs523pychen/IVS-TF2/data/tfrecords/test_test.tfrecord
2021-09-06 23:46:04,090 yolo_tf2.utils.common.read_tfr +262: INFO     [29124] Read TFRecord: /home/ivs523pychen/IVS-TF2/data/tfrecords/test_train.tfrecord
2021-09-06 23:46:05,020 yolo_tf2.utils.common.read_tfr +262: INFO     [29124] Read TFRecord: /home/ivs523pychen/IVS-TF2/data/tfrecords/test_test.tfrecord
2021-09-06 23:46:05.091359: I tensorflow/core/profiler/lib/profiler_session.cc:126] Profiler session initializing.
2021-09-06 23:46:05.091393: I tensorflow/core/profiler/lib/profiler_session.cc:141] Profiler session started.
2021-09-06 23:46:05.091503: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1611] Profiler found 1 GPUs
2021-09-06 23:46:05.091786: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcupti.so.11.2'; dlerror: libcupti.so.11.2: cannot open shared object file: No such file or directory
2021-09-06 23:46:05.091890: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcupti.so'; dlerror: libcupti.so: cannot open shared object file: No such file or directory
2021-09-06 23:46:05.091928: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1661] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI could not be loaded or symbol could not be found.
2021-09-06 23:46:05.091951: I tensorflow/core/profiler/lib/profiler_session.cc:159] Profiler session tear down.
2021-09-06 23:46:05.091993: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1752] function cupti_interface_->Finalize()failed with error CUPTI could not be loaded or symbol could not be found.
/home/ivs523pychen/.local/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py:494: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  warnings.warn('Custom mask layers require a config and must override '
WARNING:tensorflow:Model failed to serialize as JSON. Ignoring... ('Not JSON Serializable:', <yolo_tf2.core.trainer.Trainer object at 0x2aae5f197d30>)
2021-09-06 23:46:05.648286: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-09-06 23:46:05.651466: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 3000000000 Hz
Epoch 1/100
Traceback (most recent call last):
  File "train.py", line 28, in <module>
    trainer.train(
  File "/home/ivs523pychen/IVS-TF2/yolo_tf2/utils/common.py", line 61, in wrapper
    result = func(*args, **kwargs)
  File "/home/ivs523pychen/IVS-TF2/yolo_tf2/core/trainer.py", line 517, in train
    history = self.training_model.fit(
  File "/home/ivs523pychen/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1183, in fit
    tmp_logs = self.train_function(iterator)
  File "/home/ivs523pychen/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "/home/ivs523pychen/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 950, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/ivs523pychen/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3023, in __call__
    return graph_function._call_flat(
  File "/home/ivs523pychen/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1960, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/ivs523pychen/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 591, in call
    outputs = execute.execute(
  File "/home/ivs523pychen/.local/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Cannot batch tensors with different shapes in component 0. First element had shape [334,500,3] and element 1 had shape [375,500,3].
         [[node IteratorGetNext (defined at /home/ivs523pychen/IVS-TF2/yolo_tf2/core/trainer.py:517) ]] [Op:__inference_train_function_24249]

Function call stack:
train_function
```

**Standalone code to reproduce the issue**
The following is my training code
```
from yolo_tf2.core.trainer import Trainer

trainer = Trainer(
    input_shape=(416, 416, 3),
    model_configuration='yolo_tf2/config/cfg/yolov3-voc.cfg',
    classes_file='yolo_tf2/config/voc.txt',
    image_folder='data/VOC0712_TRAIN/JPEGImages/',

)

dataset_conf = {
    # 'relative_labels': 'data/tfrecords/training_data.csv',
    'xml_labels_folder': 'data/VOC0712_TRAIN/Annotations/',
    'voc_conf':'yolo_tf2/config/voc_conf.json',
    'dataset_name': 'test',
    'test_size': 0.3,
    # 'sequences': 'PRESET1',
    'augmentation': False,
}

anchors_conf = {
    # 'relative_labels': 'data/tfrecords/training_data.csv',
    'anchor_no': 9,
    'xml_labels_folder': 'data/VOC0712_TRAIN/Annotations/',
    'voc_conf':'yolo_tf2/config/voc_conf.json',
}

trainer.train(
        epochs=100, 
        batch_size=8, 
        learning_rate=1e-3, 
        dataset_name='test', 
        merge_evaluation=False,
        min_overlaps=0.5,
        new_dataset_conf=dataset_conf,  # check step 5
        new_anchors_conf=anchors_conf,  # check step 6
        weights='weights/yolov3_voc_lr3/yolov3-voc.weights'
    
)
```

**Comment by schissmantics** [comment]
Clearly there is a problem with your dataset which has different image shapes. You need to ensure all images contained in your dataset, have the same shape.

    [334,500,3] and element 1 had shape [375,500,3].

**Comment by ivs-pychen** [comment]
But the open dataset usually has different image shapes. Do I need to do some pre-processing to resize the images to the same shape?

**Comment by schissmantics** [comment]
Figure out where the shapes indicated are coming from and ensure these shapes are adjusted/expected.

**Comment by ivs-pychen** [comment]
![image](https://user-images.githubusercontent.com/65347253/132315110-d8a52734-d863-47e5-8d21-4d16dcd15f7c.png)
I use the voc xml format. I need to change the width and height in the xml files, right? Or,  I can resize the image before passing to the model.

**Comment by schissmantics** [comment]
You need to resize the different images, and adjust the labels accordingly.

**Comment by ivs-pychen** [comment]
Do you know how to modify the code to feed images with different size to the model?

**Comment by schissmantics** [comment]
If you don't know how to do it, then it's probably easier to exclude them and their respective labels.

**Comment by ivs-pychen** [comment]
Do you have some example code?

**Comment by schissmantics** [comment]
You can resize the images using [cv2.resize](https://www.tutorialkart.com/opencv/python/opencv-python-resize-image/) and modify xml using [lxml.etree](https://lxml.de/tutorial.html), you can follow the examples there. Regarding `nan`, sometimes this happens when you choose more anchors than you should, try lowering the number of anchors and I generally advise to stick with the default anchors unless you have a good reason not to.

**Comment by ivs-pychen** [comment]
OK. Thanks for your help. I will try it.

**Comment by ivs-pychen** [comment]
One more question: I try to train yolov3, and I set anchor_no to 9. The loss also become nan.

**Comment by schissmantics** [comment]
As I said, if you're not sure which number of anchor is needed, just don't pass anchor configuration and the defaults will be used. It can be one of several problems. The most common cause is you need to lower it from 9 to 6 or 3 but it could be something else which is dataset specific, i can't tell without a jupyter notebook link I can use to reproduce the issue.
