### ISSUE TITLE
Unable to load yolov4.weights 

### ISSUE THREAD

**Issue by danial880** [schissmantics/yolo-tf2#37]
<em> I was trying inference on photos with yolov4 but it is giving a Value Error while loading weights. </em>

**System information**
- Have I written custom code: No
- OS Platform and Distribution: Linux Ubuntu 18.04
- Dependency versions: tensorflow-gpu=2.6
- Python version: 3.8.12

**Standalone code to reproduce the issue**
```python
from yolo_tf2.core.detector import Detector

detector = Detector(
    input_shape=(416, 416, 3),
    model_configuration='yolo4.cfg',
    classes_file='coco.txt',
    score_threshold=0.5,
    iou_threshold=0.5,
    max_boxes=100
)

photos = ['cars.jpg']
detector.predict_photos(photos=photos,
                 trained_weights='yolov4.weights')
```
**Other info / logs** 
```
2021-09-27 07:08:01.430524: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-27 07:08:01.441808: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-27 07:08:01.442711: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-27 07:08:01,443 yolo_tf2.utils.common.activate_gpu +325: INFO     [10112] GPU activated
2021-09-27 07:08:01.462448: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-09-27 07:08:01.463012: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-27 07:08:01.463928: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-27 07:08:01.464757: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-27 07:08:02.104899: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-27 07:08:02.105757: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-27 07:08:02.106601: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-09-27 07:08:02.107359: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 10800 MB memory:  -> device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0, compute capability: 3.7
2021-09-27 07:08:04,379 yolo_tf2.utils.common.create_models +447: INFO     [10112] Training and inference models created
2021-09-27 07:08:04,379 yolo_tf2.utils.common.wrapper +64: INFO     [10112] create_models execution time: 2.9356445730009 seconds
2021-09-27 07:08:04,379 yolo_tf2.utils.common.load_weights +472: INFO     [10112] Loading pre-trained weights ...
0%      20/257717640Traceback (most recent call last):
  File "detect.py", line 13, in <module>
    detector.predict_photos(photos=photos,
  File "/home/ubuntu/anaconda3/envs/tf26/lib/python3.8/site-packages/yolo_tf2/utils/common.py", line 61, in wrapper
    result = func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tf26/lib/python3.8/site-packages/yolo_tf2/core/detector.py", line 156, in predict_photos
    self.load_weights(get_abs_path(trained_weights, verify=True))
  File "/home/ubuntu/anaconda3/envs/tf26/lib/python3.8/site-packages/yolo_tf2/utils/common.py", line 61, in wrapper
    result = func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tf26/lib/python3.8/site-packages/yolo_tf2/core/models.py", line 536, in load_weights
    layer.set_weights([convolution_weights])
  File "/home/ubuntu/anaconda3/envs/tf26/lib/python3.8/site-packages/keras/engine/base_layer.py", line 1799, in set_weights
    raise ValueError(
ValueError: Layer weight shape (3, 3, 416, 32) not compatible with provided weight shape (3, 3, 3, 32)
```

**Comment by schissmantics** [comment]
There's something wrong with the weights you're trying to load, It works perfectly fine on my end:

    2021-09-28 13:18:21,735 yolo_tf2.utils.common.create_models +447: INFO     [13188] Training and inference models created
    2021-09-28 13:18:21,736 yolo_tf2.utils.common.wrapper +64: INFO     [13188] create_models execution time: 4.529124604999993 seconds
    2021-09-28 13:18:21,737 yolo_tf2.utils.common.load_weights +472: INFO     [13188] Loading pre-trained weights ...
    100%    256672140/257717640
    2021-09-28 13:18:22,878 yolo_tf2.utils.common.load_weights +539: INFO     [13188] 
    Loaded weights: yolov4.weights ... success
    2021-09-28 13:18:22,879 yolo_tf2.utils.common.wrapper +64: INFO     [13188] load_weights execution time: 1.1421056050000118 seconds
    2021-09-28 13:18:23.037843: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
    predicting 102415438_576457599677119_4990202976577519616_n.jpg 1/1	100.0% completed
    2021-09-28 13:18:28,383 yolo_tf2.utils.common.predict_photos +190: INFO     [13188] Saved prediction: yolo-tf2/yolo_tf2/config/output/detections/predicted-90202976577519616.jpg
    2021-09-28 13:18:28,383 yolo_tf2.utils.common.wrapper +64: INFO     [13188] predict_photos execution time: 11.176294873000003 seconds
